services:
  frontend:
    restart: "no"
    build:
      context: frontend
    environment:
      VITE_API_ORIGIN: http://localhost/api
    volumes:
      - frontend:/app/frontend/dist

  mongo:
    image: mongo
    restart: "no"
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - larek-db-volume:/data/db
    networks:
      - internal
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'

  backend:
    restart: "no"
    build:
      context: backend
    env_file: ./backend/.env
    #environment:
    #  DB_ADDRESS: mongodb://root:example@mongo:27017/weblarek?authSource=admin
    #  UPLOAD_PATH: images
    #  UPLOAD_PATH_TEMP: temp
    #  ORIGIN_ALLOW: http://localhost:5173
    #  AUTH_REFRESH_TOKEN_EXPIRY: 7d
    #  AUTH_ACCESS_TOKEN_EXPIRY: 1h
    #  RATE_LIMITED: true
    #  RATE_LIMIT_POINTS: 3
    #  RATE_LIMIT_DURATION: 5
    #  RATE_LIMIT_BLOCK: 15
    volumes:
      - ./backend/src:/app/src
      - public:/app/src/public
    networks:
      - internal
    depends_on:
      - mongo

  server:
    restart: "no"
    build:
      context: nginx
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - frontend:/var/app
      - public:/var/public
    depends_on:
      - frontend
      - backend
    networks:
      - internal

volumes:
  frontend:
  public:
  larek-db-volume:

networks:
  internal:
