services:
  larek-frontend:
    container_name: larek-frontend
    image: larek-frontend-transfer
    restart: "no"
    volumes: 
      - larek-frontend-volume:/app/frontend/dist

  larek-nginx:
    container_name: larek-nginx
    image: nginx
    restart: on-failure
    volumes:
      - larek-frontend-volume:/var/app:ro
      - larek-public-volume:/var/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/server.conf:/etc/nginx/conf.d/server.conf:ro
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

  backend:
    container_name: larek-backend
    image: larek-backend-transfer
    restart: on-failure
    volumes:
      - larek-public-volume:/app/dist/public
    env_file: ./backend/.env
    expose:
      - 3000

  mongo:
    container_name: larek-mongo
    image: mongo:7
    restart: on-failure
    volumes:
      - larek-db-volume:/data/db
      - ./mongo-init/weblarek.products.json:/app/weblarek.products.json:ro
      - ./mongo-init/weblarek.users.json:/app/weblarek.users.json:ro
    expose:
      - 27017
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'

volumes:
  larek-frontend-volume:
  larek-db-volume:
  larek-public-volume:
